name: res_app
description: Restaurant App

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  equatable: ^2.0.3
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  google_fonts: ^3.0.1
  lottie: ^1.3.0
  riverpod: ^1.0.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/animations/

flutter_intl:
  enabled: false
  main_locale: en
  class_name: I18n
